### PR TITLE
Adding BatteryStatus control message 

### PR DESCRIPTION
**Pull request by efidoman**
Gets voltagea, voltageb, resistance, runtime, and temperature from transmitter

### CODE REVIEW

**Comment by efidoman** [comment]
This branch is not ready yet. Testing with a client has proven that additional work needs to be done to send the results of the battery status request back to the client. Work in progress. I might need some help figuring out exactly how to do it.

**Comment by efidoman** [comment]
I've been logging the battery status every 12 hours for 3 days now and it's working great. Also, the rssi being passed to the glucose record is working nicely.

**Comment by efidoman** [comment]
@thebookins - After your review, this branch is ready to merge now. I've been running it for a week with no issues.

**Comment by thebookins** [comment]
Looks good. Thanks @efidoman.

**Pull request merged**
